### ISSUE TITLE
allow for the calculation and display of proximity between different hotspots 

### ISSUE THREAD

**Issue by DGKSK8LIFE** [radrob1/helium-place#15]

**Comment by radrob1** [comment]
Meaning physical distance? What's the use case here?

**Comment by DGKSK8LIFE** [comment]
> Meaning physical distance?

Yes. Think it would just be useful/informative if proximity were displayed. Was a feature request from hacks happy hour.

**Comment by radrob1** [comment]
Probably need to understand this use case more. A list of nearby hotspots and their physical distance from the selected point on the map? Or the ability to select two points on the map and calculate distance?

**Comment by DGKSK8LIFE** [comment]
Both @radrob1. Was thinking of designing a new dropdown menu/card on the side of the screen with new toggle options (such as distance, topographic map, etc)

**Comment by radrob1** [comment]
Helium explorer just added a measure tool. Could do something similar. Also had a request for the hotspot hover to show nearby hotspots and distance.

**Comment by DGKSK8LIFE** [comment]
> Helium explorer just added a measure tool. Could do something similar. Also had a request for the hotspot hover to show nearby hotspots and distance.

Agreed. Want both

**Comment by radrob1** [comment]
Distance to nearby hotspots is now displayed on hotspot hover - #27
