### ISSUE TITLE
Hovering an offline hotspot throws an error

### ISSUE THREAD

**Issue by Jake0Tron** [radrob1/helium-place#81]
Because there's no reward scale for offline hotspots, trying to call `toFixed(2)` on the null value throws an error and displays incorrect information:
![image](https://user-images.githubusercontent.com/7832764/125875315-56c567db-3751-4c25-8200-29368163b241.png)
![image](https://user-images.githubusercontent.com/7832764/125875337-3da1a5f5-c3e0-46e0-8fa1-5e1ef7e5f1ae.png)
The hotspot with the popup above it is displaying the information of the other hotspot in the image.

**Comment by radrob1** [comment]
knew there was a bug there, but never dug into it. Thanks for raising it up
